branches:
  except:
    - gh-pages

dist: trusty
language: cpp
sudo: required

before_script:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get -qq update
  - sudo apt-get -y install gcc-4.9 g++-4.9 doxygen graphviz
  - pushd /home/travis/build/SaschaKaden && git clone https://github.com/SaschaKaden/IPPP_third_party.git && popd
  # cmake
  - mkdir /home/travis/build/SaschaKaden/IPPP/build && pushd /home/travis/build/SaschaKaden/IPPP/build
  - cmake -DCMAKE_BUILD_TYPE=${CONFIGURATION} -DBUILD_DOC=ON -DCMAKE_C_COMPILER=gcc-4.9 -DCMAKE_CXX_COMPILER=g++-4.9 -DCMAKE_PREFIX_PATH=/home/travis/build/SaschaKaden/IPPP_third_party ..

script: if [ "$COVERITY_SCAN_BRANCH_PATTERN" != "coverity_scan" ]; then
          make -j4 || travis_terminate 1;
          ctest || travis_terminate 1;
          fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: /html
  on:
    branch: master

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "fNKvpdrlBcq6ixwkxQbDlj6Ojvju9FdkFvHmQqVxoHP1EH+n4RnOzr1oglqXLRYlTe/v4cCxNNzXGKgzLU3xLcZ1avkhKQptj3+sQWxN3lf9FFN6pgcEn94Ct4Dv+29gEy9y43uC5+f0kDRHUL+qj0VwjKj6RJMMftJ86BjBZRX1FQV6b4y91n3R6I96uydeU3rJCk9yBdE4agFF22FEfjjKlDzFoEo61qOez0S7LV4bQUW1GtjBmgGh9pLNTcd7neFLTVjQYxp0tr5mPfEwjXJSwIWCLSoQMX0pQXMYSmpE20mcIT8h1IV++2wzoYdhr+6pM+/+axjWiF9y17Mxq9Ad1tGFDCMCRzMTHpjjGne0BOweErYvUon89YN1Rq6YwlfVS/KnK/cH3hn9CS1m7R3q8T41dLc+KxG7RP2oV781jbBew+97l+9avkRyKNYytlqI2MO8vG+W77xHGLp6W9W4Oi//bkehhuTtI8aOPeAlRarlVuzJPCoi/XuRd645T7kuz5xrqIKwoosbM98CIL00oVSVp9oFW+uSnymuQyiDZG/Ssrd6ZqGuaGaSMCFViqBVuCDQ4Q2fEmz4oqsOIm0rul7BcUqgUX5T95D07jpOAdkfSvCdHu9Im9ers6D1BYuDBLMxVw2cwfphBpWkkBpWTfI6RqBpKYVCwx1k62g="

matrix:
  include:
  # Linux
    - env: CONFIGURATION=Release
      compiler: gcc

addons:
  coverity_scan:
    project:
      name: SaschaKaden/IPPP
    notification_email: kaden.sascha@googlemail.com
    build_command_prepend: ./configure
    build_command: make
    branch_pattern: coverity_scan
