dist: trusty

language: cpp

compiler:
  - gcc

env:
  - TRAVIS_BUILD_TYPE=Debug
  - TRAVIS_BUILD_TYPE=Release
  
sudo: required

before_script:
   #eigen 3.2 support
  - hg clone https://bitbucket.org/eigen/eigen/
  - cd eigen
  - hg checkout 3.2.0
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - cd ../..
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ..
  
script: make
