dist: trusty

language: cpp

compiler:
  - gcc

env:
  - TRAVIS_BUILD_TYPE=Debug
  - TRAVIS_BUILD_TYPE=Release

sudo: required

before_script:
   #eigen 3.2 support
  - hg clone https://bitbucket.org/eigen/eigen/
  - cd eigen
  - hg checkout 3.2.0
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - cd ../..
  # libccd
  - sudo add-apt-repository --yes ppa:libccd-debs/ppa
  - sudo apt-get -qq update
  - sudo apt-get -qq --yes --force-yes install libeigen3-dev
  - sudo apt-get -qq --yes --force-yes install libccd-dev
  # octomap
  - git clone https://github.com/OctoMap/octomap
  - cd octomap
  - git checkout tags/v1.8.0
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  # fcl
  - git clone https://github.com/flexible-collision-library/fcl.git fcl
  - cd fcl
  - mkdir build
  - cd build
  - cmake -DFCL_BUILD_TESTS=OFF ..
  - make -j4
  - sudo make install
  - cd ../..
  # assimp
  - git clone https://github.com/assimp/assimp.git assimp
  - cd assimp
  - mkdir build
  - cd build
  - cmake -DASSIMP_BUILD_TESTS=OFF ..
  - make -j4
  - sudo make install
  - cd ../..
  # cmake
  - mkdir build
  - cd build
  - cmake .. #-DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ..

script: if [ "$COVERITY_SCAN_BRANCH_PATTERN" != "coverity_scan" ]; then make ; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "fNKvpdrlBcq6ixwkxQbDlj6Ojvju9FdkFvHmQqVxoHP1EH+n4RnOzr1oglqXLRYlTe/v4cCxNNzXGKgzLU3xLcZ1avkhKQptj3+sQWxN3lf9FFN6pgcEn94Ct4Dv+29gEy9y43uC5+f0kDRHUL+qj0VwjKj6RJMMftJ86BjBZRX1FQV6b4y91n3R6I96uydeU3rJCk9yBdE4agFF22FEfjjKlDzFoEo61qOez0S7LV4bQUW1GtjBmgGh9pLNTcd7neFLTVjQYxp0tr5mPfEwjXJSwIWCLSoQMX0pQXMYSmpE20mcIT8h1IV++2wzoYdhr+6pM+/+axjWiF9y17Mxq9Ad1tGFDCMCRzMTHpjjGne0BOweErYvUon89YN1Rq6YwlfVS/KnK/cH3hn9CS1m7R3q8T41dLc+KxG7RP2oV781jbBew+97l+9avkRyKNYytlqI2MO8vG+W77xHGLp6W9W4Oi//bkehhuTtI8aOPeAlRarlVuzJPCoi/XuRd645T7kuz5xrqIKwoosbM98CIL00oVSVp9oFW+uSnymuQyiDZG/Ssrd6ZqGuaGaSMCFViqBVuCDQ4Q2fEmz4oqsOIm0rul7BcUqgUX5T95D07jpOAdkfSvCdHu9Im9ers6D1BYuDBLMxVw2cwfphBpWkkBpWTfI6RqBpKYVCwx1k62g="

addons:
  coverity_scan:
    project:
      name: "SaschaKaden/RobotMotionPlanner"
      description: "Build submitted via Travis CI"
    notification_email: kaden.sascha@googlemail.com
    build_command_prepend: "make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

