#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

branches:
  except:
    - gh-pages

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\IPPP

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x64
      configuration: Release

# enable patching of AssemblyInfo.* files
#assembly_info:
#  patch: true
#  file: AssemblyInfo.*
#  assembly_version: "2.2.{build}"
#  assembly_file_version: "{version}"
#  assembly_informational_version: "{version}"

install:
  - git submodule update --init --recursive
  - vcpkg install eigen3:x64-windows
  - vcpkg install assimp:x64-windows
  - vcpkg install fcl:x64-windows
  - vcpkg install pqp:x64-windows
  - vcpkg install gtest:x64-windows
  - vcpkg install gflags:x64-windows

cache: c:\tools\vcpkg\installed\

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: x64
configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: IPPP.sln               # path to Visual Studio solution or project
  publish_wap: true               # package Web Application Projects (WAP) for Web Deploy
  publish_wap_xcopy: true         # package Web Application Projects (WAP) for XCopy deployment
  publish_azure: true             # package Azure Cloud Service projects and push to artifacts
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts

  # MSBuild verbosity level
  verbosity: normal

# scripts to run before build
before_build:
  - echo Running cmake...
  - cd c:\projects\IPPP
  - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=%P%

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:

# to disable automatic builds
#build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
  - ctest

