#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

branches:
  except:
    - gh-pages

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\IPPP

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x64
      configuration: Release

install:
  - git submodule update --init --recursive
  - cd c:\tools\vcpkg\
  - git pull
  - .\bootstrap-vcpkg.bat
  - vcpkg install eigen3:x64-windows
  - vcpkg install assimp:x64-windows
  - vcpkg install fcl:x64-windows
  - cd c:\projects\IPPP

cache: c:\tools\vcpkg\installed\ -> appveyor.yml

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: x64
configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: IPPP.sln               # path to Visual Studio solution or project
  publish_wap: true               # package Web Application Projects (WAP) for Web Deploy
  publish_wap_xcopy: true         # package Web Application Projects (WAP) for XCopy deployment
  publish_azure: true             # package Azure Cloud Service projects and push to artifacts
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts

# MSBuild verbosity level
  verbosity: normal

# scripts to run before build
before_build:
  - echo Running cmake...
  - cd c:\projects\IPPP
  - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
  - ctest
